GRANT SELECT, INSERT, UPDATE ON OPENBILL_CATEGORIES TO public;
GRANT SELECT, INSERT, DELETE  ON OPENBILL_ACCOUNTS TO public;
GRANT UPDATE ( locked_at) ON OPENBILL_ACCOUNTS TO public;
GRANT SELECT, INSERT ON OPENBILL_TRANSACTIONS TO public;
GRANT SELECT, INSERT, UPDATE, DELETE ON openbill_policies TO public;

GRANT INSERT ON OPENBILL_HOLDS TO public;
