GRANT SELECT, INSERT, UPDATE ON OPENBILL_CATEGORIES TO public;
GRANT SELECT, INSERT, UPDATE ON OPENBILL_ACCOUNTS TO public;
GRANT SELECT, INSERT, UPDATE ON OPENBILL_TRANSACTIONS TO public;
GRANT SELECT, INSERT, UPDATE ON openbill_invoices TO public;
GRANT SELECT, INSERT, UPDATE ON openbill_policies TO public;
