name: Test openbill-core
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          # required
          POSTGRES_PASSWORD: postgres

    steps:
    - name:
      uses: actions/checkout@v2
    - name: Make tests
      run: export PG_PASSWORD=postgres bash run_all_tests.sh
